name: Docker

on:
  push:
     branches:
      - 'main'
      
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: crbrezyweatherprod001.azurecr.io/demowebapp:0.0.1          
