name: Build and push BrezyWeather image

on:
  push:
     branches: 
      - 'main'

env:
  IMAGE_REPOSITORY_NAME: demowebapp
  IMAGE_TAG: 1.0.0
  
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          #tags example: cbbrezyweatherprodxxx.azurecr.io/demowebapp:0.0.1
          tags: ${{ secrets.ACR_SERVER }}/${{ IMAGE_REPOSITORY_NAME }}:${{ IMAGE_TAG }}          
